// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let token = data.session?.access_token
    if (!token && typeof localStorage !== 'undefined') {
      const devGuest = localStorage.getItem('dev_guest_session')
      if (devGuest) {
        try {
          token = JSON.parse(devGuest).access_token
        } catch {}
      }
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
